name: log4d
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Caijinglong <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  args: ^1.5.1
  shelf: ^0.7.4
  shelf_web_socket: ^0.2.2+4

dev_dependencies:
  test: ^1.0.0

executables:
  log4j: