name: log4d
description: A log library. Open command-line server application. Support as package. Can help save your flutter or dart log to file. 
version: 1.0.3
homepage: https://github.com/CaiJingLong/log4d
author: Caijinglong <cjl_spy@163.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  args: ^1.5.1
  shelf: ^0.7.4
  shelf_web_socket: ^0.2.2+4

dev_dependencies:
  test: ^1.0.0

executables:
  log4d:
  log4d_client: